# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pollee' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Pollee

  target 'PolleeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PolleeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
